/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;

class LibraryTest {
    @Test
    void rollTest() {
        Library sut = new Library();
        int[] actualOutput = sut.roll(5);
        assertEquals(5, actualOutput.length, "length of array should be 5");

        for (int roll : actualOutput) {
            assertTrue(roll >= 1 && roll <= 6, "Roll values should all be between 1 and 6");
        }
    }

    @Test
    void containsDuplicatesTest() {
        Library sut = new Library();
        int[] testOne = {1, 3, 4, 7, 9}; //should return false
        int[] testTwo = {1, 3, 4, 7, 3}; //should return true
        boolean actualOutputOne = sut.containsDuplicates(testOne);
        boolean actualOutputTwo = sut.containsDuplicates(testTwo);

        assertFalse(actualOutputOne, "Should return false");
        assertTrue(actualOutputTwo, "should return true");
    }

    @Test
    void averageTest() {
        Library sut = new Library();
        int[] testOne = {1, 3, 4, 7, 9}; //should return 4.8
        int[] testTwo = {1, 3, 4, 7, 3}; //should return 3.6
        double actualOutputOne = sut.average(testOne);
        double actualOutputTwo = sut.average(testTwo);

        assertTrue(actualOutputOne > 4 && actualOutputOne < 5, "Output should be 4.8");
        assertTrue(actualOutputTwo > 3 && actualOutputTwo < 4, "Output should be 3.6");

    }

    @Test
    void lowestAverageTest() {
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] expectedArray = {55, 54, 60, 53, 59, 57, 61};
        int[] actualOutput = sut.lowestAverage(weeklyMonthTemperatures);

        assertArrayEquals(expectedArray, actualOutput, "Array should be {55, 54, 60, 53, 59, 57, 61}");
    }
}